### ISSUE TITLE
look like your system is not a raspberry 

### ISSUE THREAD

**Issue by bastianorts** [hackthedev/remotepifm#5]
I get the : look like your system is not a raspberry when I try to connect

**Comment by hackthedev** [comment]
This happens when the default directory after connecting to the machine is not `/home/pi`. [See here](https://github.com/hackthedev/remotepifm/blob/b28b216fe3d5f15aa94a95f98d3eae5595da4e68/app/src/main/java/com/adsoleware/remotepifm/MainActivity.java#L149)

Possible reason for this is that you try to login with a user thats not named "pi" or doesnt have its home directory located at `/home/pi`

You can bypass this issue by either creating a new account named pi, which creates the path `/home/pi` automatically and log in with this account, or you create this directory path yourself and change its default home directory.
